courses = [
    {
        "_id": "1",
        "name": "Data Science and Machine Learning with Python - Hands On!",
        "duration": "08 hr 15 mins",
        "price": "385.00",
        "category": "Science",
        "image": "/images/courses/courses-01.jpg",
        "rating": "4.5",
        "numReview": "28",
        "author": "Jason Williams",
    },
    {
        "_id": "2",
        "name": "Create Amazing Color Schemes for Your UX Design Projects",
        "duration": "08 hr 15 mins",
        "price": "420.00",
        "category": "Science",
        "image": "/images/courses/courses-02.jpg",
        "rating": "4.8",
        "numReview": "28",
        "author": "Pamela Foster",
    },
    {
        "_id": "3",
        "name": "Culture & Leadership: Strategies for a Successful Business",
        "duration": "08 hr 15 mins",
        "price": "285.00",
        "category": "Commerce",
        "image": "/images/courses/courses-03.jpg",
        "rating": "4.5",
        "numReview": "28",
        "author": "Rose Simons",
    },
]
